[package]
name = "aircraft_sim"
version = "0.1.0"
authors = ["SuedeG <ymp17kwu@uea.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
